project:
  output-dir: _site/en

website:
  description: "Personal website of Alain Quartier-la-Tente (AQLT), administrator of the Insee"
  navbar:
    # left:
    #   - href: index.qmd
    #     text: Home

    right:
      - href: aboutme.qmd
        text: About me
      - href: CV.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: blog/index.qmd
        text: Blog
      - href: ../
        text: FR
        icon: translate

lang: en

