---
title: "Curriculum vitæ"
---

## {{< fa briefcase >}} Expérience professionnelle 

:::: {.columns}
::: {.column width="10%"}
2021-
:::
::: {.column width="90%"}
**Chargé d'études macroéconomiques**,
[Insee](https://www.insee.fr){target="_blank"}, Paris.
:::
::::


:::: {.columns}
::: {.column width="10%"}
Été
2020
:::
::: {.column width="90%"}
**Stagiaire dans la cellule Recherche et Développement de la [NBB](https://www.nbb.be/fr){target="_blank"} (National Bank of Belgium)**, Bruxelles, Belgique.  
<!-- Étude de l'apport des filtres asymétriques dans la détection en temps réel des points de retournement. -->
:::
::::

:::: {.columns}
::: {.column width="10%"}
2017 - 2019
:::
::: {.column width="90%"}
**Méthodologue sur les corrections des variations saisonnières**,
[Insee](https://www.insee.fr){target="_blank"}, Paris.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2019 -
:::
::: {.column width="90%"}
**Référé des revues** [Statéco](https://www.insee.fr/fr/information/2116798){target="_blank"},
_[Journal of Official Statistics](https://www.scb.se/jos){target="_blank"}_,
_[Statistical Journal of the IAOS](https://officialstatistics.com){target="_blank"}_ 
et 
_[International Journal of Operational Research](https://www.inderscience.com/jhome.php?jcode=ijor){target="_blank"}_.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2015 - 2017
:::
::: {.column width="90%"}
**Responsable du suivi de l’activité conjoncturelle dans l’industrie**, [Insee](https://www.insee.fr){target="_blank"}, Paris.
:::
::::


:::: {.columns}
::: {.column width="10%"}
Été
2013
:::
::: {.column width="90%"}
**Stagiaire dans le service des relations internationales de l'[INE](https://www.ine.es){target="_blank"} (Instituto Nacional de Estadística)**, Madrid, Espagne.
<!-- Étude d’indicateurs économiques et financiers des *Special Data Dissemination Standard* (SDDS) — Norme Spéciale de Diffusion de Données — du FMI. -->
:::
::::

## {{< fa user-graduate >}} Formation 

:::: {.columns}
::: {.column width="10%"}
2020 -
:::
::: {.column width="90%"}
**Doctorant à l’École Doctorale de Gestion et d’Economie ([EDGE](https://ed-edge.doctorat-bretagneloire.fr){target="_blank"}), Laboratoire d’Économie et de Management de Nantes Atlantique ([LEMNA](https://lemna.univ-nantes.fr){target="_blank"})**.

- Détection en temps réels des points de retournement : apport de l’utilisation des filtres asymétriques dans l’analyse conjoncturelle.  
- Sous la direction d’Olivier Darné (LEMNA) et Dominique Ladiray (Insee).
:::
::::

:::: {.columns}
::: {.column width="10%"}
2019 - 2021
:::
::: {.column width="90%"}
**École Nationale de la Statistique et de l’Administration Économique** ([ENSAE](https://www.ensae.fr){target="_blank"}).
:::
::::

:::: {.columns}
::: {.column width="10%"}
2014 - 2015
:::
::: {.column width="90%"}
**Master 2 de statistique-économétrie, spécialité statistique publique, parcours études statistiques**, [ENSAI](http://ensai.fr){target="_blank"}
/ [Université Rennes 1](https://math.univ-rennes1.fr){target="_blank"}.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2013 - 2014
:::
::: {.column width="90%"}
**Licence Sciences des organisations et des marchés, mention économie appliquée**, [Université Paris-Dauphine](https://dauphine.psl.eu/formations/licences/economie-appliquee){target="_blank"}.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2012 - 2013
:::
::: {.column width="90%"}
**Licence Sciences, technologies, santé, mention mathématiques**,
[Université Rennes 1](https://math.univ-rennes1.fr/licence-mention-mathematiques){target="_blank"}.
:::
::::


:::: {.columns}
::: {.column width="10%"}
2012 - 2014
:::
::: {.column width="90%"}
**École Nationale de la Statistique et de l’Analyse de l’Information**  ([ENSAI](http://ensai.fr){target="_blank"}).
:::
::::

:::: {.columns}
::: {.column width="10%"}
2010 - 2012
:::
::: {.column width="90%"}
**Classes préparatoires aux grandes écoles, filière MPSI (Maths, Physique, Sciences de l’Ingénieur) puis MP* (Mathématiques Physique)**, option informatique, [Lycée Carnot](http://lyc21-carnot.ac-dijon.fr){target="_blank"}, Dijon.
:::
::::



## {{< fa newspaper >}} Publications / Interventions

### Publications

* Quartier-la-Tente A. (2024), « Estimation en temps réel de la tendance-cycle : apport de l’utilisation des moyennes mobiles asymétriques\ », *[Document de travail méthodologique de l'Insee](https://github.com/InseeFrLab/DT-est-tr-tc){target="_blank"}*.

  ::: {.callout-resume .callout-warning collapse=true}
  ### Résumé
  Cette étude s’intéresse à différentes méthodes de construction de moyennes mobiles pour l’estimation en temps réel de la tendance-cycle et la détection rapide des points de retournement. Nous proposons une comparaison des principales méthodes, en s’appuyant sur une formulation générique de construction de moyennes mobiles. Nous décrivons également deux prolongements possibles aux filtres polynomiaux locaux : l’ajout d’un critère permettant de contrôler le déphasage (délai dans la détection des points de retournement) et une façon de paramétriser localement ces filtres. La comparaison empirique des méthodes montre que : les problèmes d’optimisation de filtres issus des espaces de Hilbert à noyau reproduisant (RKHS) augmentent le déphasage et les révisions des estimations de la tendance-cycle ; modéliser des tendances polynomiales trop complexes introduit plus de révisions sans diminuer le déphasage ; pour les filtres polynomiaux, une paramétrisation locale permet une réduction des révisions et du délai de détection des points de retournement.

  Cette étude est entièrement reproductible et tous les codes sont disponibles sous <https://github.com/InseeFrLab/DT-est-tr-tc>.
  :::

* Babet D., Lequien M., Quartier-la-Tente A. (2022), « L'apport des modèles macroéconomiques pour simuler les effets du renchérissement des prix d’importation de l'énergie\ », *[Note de conjoncture](https://www.insee.fr/fr/statistiques/6215280?sommaire=6215395){target="_blank"}*, mars, p. 16-18.

* Quartier-la-Tente A. (2022), « Estimation en temps réel de la tendance-cycle : apport de l’utilisation des filtres asymétriques dans la détection des points de retournement\ », *[14e Journées de Méthodologie Statistique](http://www.jms-insee.fr/2022/S27_2_ACTE_QUARTIERLATENTE_JMS2020.pdf){target="_blank"}*.

* Ladiray D. et Quartier-la-Tente A. (2018), « Du bon usage des modèles Reg-ARIMA en désaisonnalisation\ », *[13e Journées de Méthodologie Statistique](http://www.jms-insee.fr/2018/S05_1_ACTEv3_QUARTIERLATENTE_JMS2018.pdf){target="_blank"}*.

  ::: {.callout-resume .callout-warning collapse=true}
  ### Résumé
  Les modèles de régression avec erreurs ARIMA (Reg-ARIMA) sont aujourd’hui largement utilisés en désaisonnalisation. Ils permettent notamment d’enlever certains effets déterministes présents dans la série (points atypiques, ruptures, effets de calendrier) avant de la décomposer en tendance-cycle, saisonnalité et irrégulier.

  Les principaux logiciels d’ajustement saisonnier (X-13ARIMA-SEATS, TRAMO-SEATS, JDemetra+) mettent en œuvre ces modèles de façon automatique et conviviale. Cette facilité cache en fait une complexité réelle et dans certains cas un manque de robustesse qui peut échapper à l’utilisateur... et aux tests statistiques.

  Dans cette article, nous illustrons les réelles difficultés de mise en œuvre de ces modèles à travers des cas concrets : l’estimation d’un effet d’année bissextile, l’estimation de ruptures et l’identification d’un modèle ARIMA.
  :::


* Pham H. et Quartier-la-Tente A. (2018), « Désaisonnaliser les séries très longues par sous-période, gains et choix de la longueur de traitement\ », *[13e Journées de Méthodologie Statistique](http://www.jms-insee.fr/2018/S05_2_ACTEv3_PHAM_JMS2018.pdf){target="_blank"}*.

  <!-- Keep two space to preserve bullet list and CSS formatting -->
  ::: {.callout-resume .callout-warning collapse=true}
  ### Résumé
  Sur longue période, les institutions, les normes de sociétés ainsi que les comportements des agents économiques évoluent, induisant des changements dans la dynamique des séries écono- miques que l’on étudie. Ainsi, on admet l’idée que les séries temporelles d’une longueur dépassant les 20 années présentent en général un profil changeant. Ces changements pouvant concerner les effets de calendrier (activités les dimanches et jours fériés par exemple), la saisonnalité ou la corrélation temporelle entre observations éloignées modélisée par une fonction ARIMA. Dans ce cas, réaliser une désaisonnalisation sur les séries longues risque de produire des résultats sous-optimaux, en particulier sur les périodes les plus récentes et les plus anciennes.
  
  Le premier objectif de cet article est d’examiner si couper les séries longues permet effectivement d’améliorer la qualité de la désaisonnalisation. Les résultats qui sont présentés s’appuient sur une étude empirique des séries de l’indice de la production industrielle (IPI) qui sont longues de 27 années, de janvier 1990 à décembre 2017. En coupant ces séries en deux sous-périodes au point de janvier 2005 afin de désaisonnaliser par sous-période, nous constatons que la qualité de la phase de pré-ajustement s’améliore. Cette phase concerne la détection des outliers, la cor- rection des effets de calendrier et l’estimation d’un modèle ARIMA. En revanche, on constate qu’il n’y a pas de différence sur l’appréciation de la qualité de la décomposition réalisée par la méthode non-paramétrique X11, quand bien même les résultats de la décomposition obtenus sont différents.
  
  Par ailleurs, le choix de la date de coupure est lui-même un problème à résoudre. Ce choix peut être guidé par des informations sur les changements de gestion des données, sur les révisions de méthodes statistiques appliquées, sur les chocs connus de nature économique et institutionnelle ou encore il peut simplement résulter de contraintes de production. Autrement dit, le choix peut être effectué à l’aide d’informations qualitatives existant en dehors des données et de ma- nière indépendantes des données. L’autre objectif de cet article est justement d’examiner s’il est possible de proposer un moyen de choisir une date de coupure qui soit fondée sur l’étude des données.
  :::

* Dortet-Bernadet V., Lenseigne F., Parent C., Quartier-la-Tente A., Stoliaroff-Pépin A-M. et Plouhinec C. (2016), « Après deux ans de turbulences, le secteur aéronautique français peut redécoller\ », *[Note de conjoncture](https://www.insee.fr/fr/statistiques/fichier/2531682/122016_d1.pdf){target="_blank"}*, décembre, p. 19-37.

<!-- Keep two space to preserve bullet list and CSS formatting -->
  ::: {.callout-resume .callout-warning collapse=true}
  ### Résumé
  L’objectif de ce dossier est d’analyser la conjoncture récente du secteur aéronautique. Ses effets d’entraînement sur l’activité nationale française s’y révèlent plus importants qu’ailleurs et l’économie française s’avère la plus dépendante aux fluctuations de la demande mondiale d’avions. Pourtant, la construction aéronautique française n’a pas profité du récent essor du trafic aérien et s’est repliée en 2014 et 2015. Ce repli tient à la fois à des problèmes d’offre (constructeurs et équipementiers à la limite de leur capacité de production, problèmes d’approvisionnement) et de demande (notamment pour les avions d’affaires et d’hélicoptères). Toutefois, ces problèmes semblent se résoudre peu à peu fin 2016 : production et exportations aéronautiques peuvent maintenant redécoller, ne serait-ce que pour rattraper le retard accumulé dans les livraisons.
  :::

* Glotain M. et Quartier-la-Tente A. (2015), « De nouveaux indicateurs de climats des affaires sous-sectoriels pour améliorer le diagnostic conjoncturel\ », *[Note de conjoncture](https://www.insee.fr/fr/statistiques/fichier/2019067/062016_d2.pdf){target="_blank"}*, juin, p. 35-56.

  ::: {.callout-resume .callout-warning collapse=true}
  ### Résumé
  L’objectif de ce dossier est de proposer de nouveaux indicateurs de climats des affaires pour améliorer le diagnostic conjoncturel. Ces indicateurs synthétiques permettent de résumer l’information commune aux soldes d’opinion collectés dans les enquêtes de conjoncture. En plus du climat des affaires « France\ » des climats pour les principaux secteurs marchands (industrie, bâtiment, commerce, services) étaient déjà publiés. Dans ce dossier, une désagrégation plus importante encore est proposée, avec des climats sous-sectoriels. Dans l’industrie, cela permet de distinguer par exemple le climat dans l’agroalimentaire et celui dans l’automobile. Ces climats sous-sectoriels apportent une information pertinente pour l’analyse : ils améliorent la lecture des soldes d’opinion ; ils permettent d’obtenir des prévisions satisfaisantes de l’activité des sous-branches correspondantes ; ils fournissent également, pour l’industrie dans son ensemble, des prévisions plus précises que les modèles utilisés jusqu’à présent. Ces nouveaux indicateurs de climats sous-sectoriels sont depuis systématiquement publiés dans les publications sur les enquêtes de conjoncture.
  :::

* Quartier-la-Tente A. (2015), « Dans quelle mesure l’intégration d’informations sous-sectorielles permet-elle d’améliorer la qualité de la prévision de la production manufacturière ?\ », mémoire de master, miméo.



### Interventions

- {{< fa brands r-project >}} package `tvCoef`, implementing time-varying coefficients models has never been so easy (2023), [Workshop on Time Series Analysis and Statistical Disclosure Control Methods for Official Statistics](https://aqlt.github.io/slides/2023%20-%2012%20-%20OECD/Slides_AQLT.pdf){target="_blank"}.

- Avec Abbas R. , Carnot N., Lequien M., Roux S., L'effet macro-économique de la transition bas carbone (2023), Séminaire D2E.

- Manipuler les moyennes mobiles avec R et JDemetra+ (2023), [Rencontres R](https://aqlt.github.io/slides/2023%20-%2006%20-%20Rencontres%20R/Slides_AQLT.pdf){target="_blank"}.

- Avec [du Campe de Rosamel C.](https://www.linkedin.com/in/claire-de-rosamel-61a046202/) (stagiaire encadrée pendant 6 mois), Utilisation de modèles de régression à coefficients variant dans le temps pour la prévision conjoncturelle (2023), [Atelier D2E](https://aqlt.github.io/AteliertvCoef/){target="_blank"}.


- R and JDemetra+ 3.0: A new toolbox around seasonal adjustment and time series analysis (2022), [2nd Workshop on Time Series Methods for Official Statistics](https://aqlt.github.io/slides/2022%20-%2009%20-%20OECD/Slides_AQLT.pdf){target="_blank"}, [uRos](https://aqlt.github.io/slides/2022%20-%2011%20-%20uRos/Slides_AQLT.pdf){target="_blank"}.

- Trend-cycle extraction and moving average manipulations in R with the rjdfilters package (2022), [4th Seasonal Adjustment Practitioners Workshop](https://aqlt.github.io/slides/2022%20-%2006%20-%20SAPW/Slides_AQLT.pdf){target="_blank"}.

- Estimation en temps réel de la tendance-cycle : Apport de l’utilisation des filtres asymétrique (2022), [1ère Journée d'Économétrie Appliquée « Michel TERRAZA »](https://aqlt.github.io/slides/2022%20-%2005%20-%20JEAMT/Slides_AQLT.pdf){target="_blank"}.

- Performance of asymmetric filters for trend-cycle extraction - Application to the COVID-19 crisis (2021), [JSM (2021)](https://ww2.amstat.org/meetings/jsm/2021/onlineprogram/AbstractDetails.cfm?abstractid=317462){target="_blank"}.

- Performance of asymmetric filters for trend-cycle extraction - Application to the COVID-19 crisis (2021), [New Techniques and Technologies for Statistics  (NTTS)](https://aqlt.github.io/slides/2021%20-%2003%20-%20NTTS/Slides.pdf){target="_blank"}.

- Animation et participation à un Hackathon sur RJDemetra (deux jours, 2019), Deutsche Bundesbank, Francfort.

- RJDemetra: an R interface to JDemetra+ (2019), [Seasonal Adjustment Center of Excellence (SACE) Meeting #6](https://ec.europa.eu/eurostat/cros/system/files/point_3_-_rjdemetra.pdf), [New Techniques and Technologies for Statistics  (NTTS)](https://ec.europa.eu/eurostat/cros/system/files/190315_rjdemetra.pdf){target="_blank"}, Seasonal Adjustment Expert Group (SAEG), [useR!2019](http://user2019.r-project.org/static/pres/t256274.pdf){target="_blank"}.

- Avec Ladiray D., (In)Stability of Reg-ARIMA Models for Seasonal Adjustment (2019), *[New Techniques and Technologies for Statistics  (NTTS)](https://ec.europa.eu/eurostat/cros/system/files/point_7.1_-_insee_-_instability_of_reg-arima_estimations.pdf){target="_blank"}*.

- R and JDemetra+: RJDemetra and rjdqa (2018), [Seasonal Adjustment Center of Excellence (SACE) Meeting #5](https://ec.europa.eu/eurostat/cros/system/files/point_6.2_-_insee_-_rjdemetra.pdf).


## {{< fa chalkboard-teacher >}} Enseignements 


:::: {.columns}
::: {.column width="10%"}
2023-
:::
::: {.column width="90%"}
**Cours d'algèbre** pour la préparation du [concours interne d'administrateurs de l'Insee](https://www.insee.fr/fr/information/4773743){target="_blank"} (32h), Paris.
:::
::::


:::: {.columns}
::: {.column width="10%"}
2022-
:::
::: {.column width="90%"}
**Analyse des séries temporelles avec {{< fa brands r-project >}}**,
[CEPE](https://www.lecepe.fr/formations/methodes-statistiques/series-temporelles/analyse-des-series-temporelles-avec-r_44.html){target="_blank"}, Paris.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2021-2022
:::
::: {.column width="90%"}
**Chargé de travaux pratiques d'analyse des séries temporelles**, [ENSAE](https://www.ensae.fr){target="_blank"}, 
Paris.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2021
:::
::: {.column width="90%"}
**Désaisonnalisation avec JDemetra+ et RJDemetra**
(24h), RTE, Paris.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2019-
:::
::: {.column width="90%"}
**Formation désaisonnaliser une série temporelle**
(24h),
[CEPE](https://www.lecepe.fr/formations/methodes-statistiques/series-temporelles/desaisonnaliser-une-serie-temporelle_42.html){target="_blank"}, Paris.
:::
::::

:::: {.columns}
::: {.column width="10%"}
2017 - 2019
:::
::: {.column width="90%"}
**Formations sur la correction des variations saisonnières et des jours ouvrables (CVS-CJO)**, [Insee](https://www.insee.fr){target="_blank"},
Paris.
:::
::::


:::: {.columns}
::: {.column width="10%"}
2016
:::
::: {.column width="90%"}
**Chargé de travaux pratiques d’initiation à {{< fa brands r-project >}}**, [ENSAE](https://www.ensae.fr){target="_blank"}, 
Paris.
:::
::::

## {{< fa globe-europe >}} Coopérations

:::: {.columns}
::: {.column width="10%"}
**Maurice** (2023)
:::
::: {.column width="90%"}
Assistance technique sur la production d'indicateurs mensuels d'activité économiques (IMAE).
:::
::::

:::: {.columns}
::: {.column width="10%"}
**Cameroun** (2023)
:::
::: {.column width="90%"}
Assistance technique sur la production de comptes nationaux trimestriels désaisonnalisés et corrigés des effets jours ouvrables.
:::
::::


:::: {.columns}
::: {.column width="10%"}
**Togo** (2023)
:::
::: {.column width="90%"}
Assistance technique sur la production de comptes nationaux trimestriels et d'indicateurs mensuels d'activité économiques désaisonnalisés et corrigés des effets jours ouvrables.
:::
::::


:::: {.columns}
::: {.column width="10%"}
**Mauritanie** (2022)
:::
::: {.column width="90%"}
Assistance technique sur la construction d'indice de production industrielle (IPI) et sur la désaisonnalisation
:::
::::

:::: {.columns}
::: {.column width="10%"}
**Macédoine du Nord** (2022)
:::
::: {.column width="90%"}
Assistance technique sur les prévisions de liquidités auprès de la Banque centrale de Macédoine du Nord.
:::
::::


:::: {.columns}
::: {.column width="10%"}
**Honduras** (2022)
:::
::: {.column width="90%"}
Assistance technique sur les prévisions de liquidités auprès de la Banque centrale du Honduras.
:::
::::


:::: {.columns}
::: {.column width="10%"}
**Sénégal** (2020)
:::
::: {.column width="90%"}
Formation sur le traitement et la prévision de séries temporelles avec le logiciel {{< fa brands r-project >}},
[BCEAO](https://www.bceao.int){target="_blank"}.
:::
::::

:::: {.columns}
::: {.column width="10%"}
**Europe** (2017-)
:::
::: {.column width="90%"}
Membre du centre d'excellence en désaisonnalisation d'Eurostat : réflexions sur les méthodes de désaisonnalisation ; développement de packages R autour de JDemetra+, maintenance et distribution. Assistance technique à plusieurs pays européens.
:::
::::

:::: {.columns}
::: {.column width="10%"}
**Paris** (2018)
:::
::: {.column width="90%"}
Assistance technique à une délégation serbe sur les méthodes de désaisonnalisation.
:::
::::

:::: {.columns}
::: {.column width="10%"}
**Sénégal** (2017)
:::
::: {.column width="90%"}
Formation sur la construction de modèles de prévisions et d’indicateurs synthétiques, [BCEAO](https://www.bceao.int){target="_blank"}, Dakar, et [Insee](https://www.insee.fr){target="_blank"},
Paris.
:::
::::


:::: {.columns}
::: {.column width="10%"}
**Paris** (2016)
:::
::: {.column width="90%"}
Assistance technique à une délégation serbe sur l'utilisation des enquêtes de conjoncture pour la prévision.
:::
::::

Term 1
:   Definition 1
