on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        author: 'Carlos Scheidegger'
        description: 'This action will render an existing quarto project'
        runs:
          using: 'composite'
          steps:
            - name: 'Render'
              env:
                QUARTO_PRINT_STACK: true
              run: |
                quarto render . --profile fr
                quarto render . --profile en
                if [ -f "_book" ]; then
                  echo "QUARTO_OUTPUT=_book" >> $GITHUB_ENV
                elif [ -f "_site" ]; then
                  echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
                fi
              shell: bash
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
